server:
  port: 8080

security:
  key: ${JWT_SECRET_KEY}

meal_api:
  meal:
    start_id: 52802
    end_id: 53603
    pulled_amount: 100
  ingredient:
    fields_amount: 20


spring:
  jpa:
    show-sql: false
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver